# Generated by Django 4.2.5 on 2023-09-15 15:42

import Books.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('authors', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('action', models.CharField(max_length=20)),
                ('fees', models.CharField(blank=True, max_length=20)),
                ('book', models.ForeignKey(null=True, on_delete=models.SET(Books.models.get_sentinel_book), to='Books.book')),
                ('member', models.ForeignKey(null=True, on_delete=models.SET(Books.models.get_sentinel_user), to='Books.member')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Books.member'),
        ),
    ]
